SELECT 
PRC.IDPROC, 
PRC.CODPRC, 
PRC.DESCRABREV, 
PRC.DHALTER,
PRC.VERSAO,
ATV.IDEFX, 
LMP.CODPRODPA,
PROPA.DESCRPROD DESCRPRODPA, 
LMP.CODPRODMP, 
PROMP.DESCRPROD DESCRPRODMP, 
LMP.QTDMISTURA, 
LMP.CODVOL, 
PROMP.USOPROD,
(SELECT SUM(LMP1.QTDMISTURA) FROM TPRLMP LMP1
  WHERE LMP1.IDEFX = ATV.IDEFX AND LMP1.CODPRODPA = LMP.CODPRODPA 
    AND LMP1.CODPRODMP NOT IN (SELECT CODPROD 
                                FROM TGFPRO WHERE DESCRPROD LIKE '%SERVICO%'
                                AND USOPROD = 'P') ) TOTAL_MISTURA,
ROUND((LMP.QTDMISTURA*100)/
(SELECT SUM(LMP1.QTDMISTURA)
     FROM TPRLMP LMP1  WHERE LMP1.IDEFX = ATV.IDEFX 
     AND LMP1.CODPRODPA = LMP.CODPRODPA 
     AND LMP1.CODPRODMP NOT IN (SELECT CODPROD
                                 FROM TGFPRO WHERE DESCRPROD LIKE '%SERVICO%'
                                 AND USOPROD = 'P') ),2) PERCMP,
(SELECT nvl(MAX(SEQ),0) FROM AD_FCICOMP WHERE NUNICO = :P_NUNICO) SEQCOMP
                                
 FROM TPRPRC PRC
 LEFT JOIN TPRATV ATV ON ATV.IDPROC = PRC.IDPROC 
 LEFT JOIN TPRLMP LMP ON LMP.IDEFX = ATV.IDEFX 
 LEFT JOIN TGFPRO PROMP ON PROMP.CODPROD = LMP.CODPRODMP
 LEFT JOIN TGFPRO PROPA ON PROPA.CODPROD = LMP.CODPRODPA
 WHERE PRC.IDPROC = (SELECT MAX(IDPROC) FROM TPRPRC
                 WHERE CODPRC = 312 /*PROCESSO TERCEIROS*/
                 AND DHCAD <= (SELECT ADD_MONTHS(REFERENCIA,-2)  FROM AD_FCICAB WHERE NUNICO =:P_NUNICO ))
 AND LMP.CODPRODMP NOT IN  ((SELECT CODPROD FROM 
                            TGFPRO WHERE DESCRPROD 
                            LIKE '%SERVICO%'AND USOPROD = 'P') )
                            AND PROPA.ATIVO = 'S'
 ORDER BY CODPRODPA ASC