SELECT * FROM (SELECT 
CAB.CODPARC, 
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.CODTIPOPER, 
TOP.DESCROPER, 
ITE.CODPROD, 
ITE.QTDNEG, 
ITE.VLRUNIT,
ITE.CONTROLE,
ITE.VLRICMS,
ITE.CODVOL,
ITE.VLRTOT,
ITE.SEQUENCIA,
CAB.DTENTSAI,
to_char((SELECT 
    REGEXP_SUBSTR(
        T.XML,
         '<nLote>'||ITE.CONTROLE||'</nLote>.*?<orig>([^<]+)</orig>',  -- Expressão para capturar <orig>
        1,                                                    
        1,                                                      
        NULL,                                               
        1                                                       
    ) AS ORIGEM
FROM TGFIXN T
WHERE REGEXP_LIKE(
    T.XML, 
    '<nLote>'||ITE.CONTROLE||'</nLote>'                            
) AND T.NUNOTA = CAB.NUNOTA
)) as ORIGPROD



FROM TGFITE ITE 
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                     AND TOP.DHALTER = CAB.DHTIPOPER
INNER JOIN TGFIXN IXN ON IXN.NUNOTA = CAB.NUNOTA
WHERE ITE.CODPROD IN (SELECT DISTINCT CODPRODMP FROM AD_FCICOMP WHERE NUNICO = :P_NUNICO)
AND CAB.DTENTSAI >= (SELECT ADD_MONTHS(REFERENCIA,-2)  FROM AD_FCICAB WHERE NUNICO =:P_NUNICO)
AND CAB.DTENTSAI <= (SELECT LAST_DAY(ADD_MONTHS(REFERENCIA,-2))  FROM AD_FCICAB WHERE NUNICO =:P_NUNICO)
AND TOP.ATUALEST = 'E'
AND TOP.ATUALESTTERC = 'N'
AND TOP.TIPMOV IN ('C' )
AND CAB.CODPARC NOT IN (1,2,3,4,5,6,7,8,9,10,11,12,13)
AND CAB.CODEMP = (SELECT CODEMP FROM AD_FCICAB WHERE NUNICO = :P_NUNICO)
AND CAB.STATUSNOTA = 'L'
ORDER BY CAB.DTENTSAI
)