SELECT 
CODPRODPA, 
VLRCOMERC, 
VLRPARCIMP,
ORIGPRODATUAL,
PERCIMPORTADO,
CASE WHEN PERCIMPORTADO > 0 AND PERCIMPORTADO <=40 THEN '5'
WHEN PERCIMPORTADO >40 AND PERCIMPORTADO <=70 THEN '3' 
WHEN PERCIMPORTADO >70 THEN '8' 
WHEN PERCIMPORTADO = 0 THEN '0'
ELSE '0' END AS ORIGPROD,
OLDVLRCOMERC,
VLRPARCIMPEXT
FROM 
(SELECT DISTINCT 
CODPRODPA,
NVL((SELECT VLRMEDIO 
    FROM AD_FCISAIDA 
    WHERE NUNICO = COM.NUNICO
    AND CODPROD = COM.CODPRODPA),0) VLRCOMERC,
NVL((SELECT SUM(VLRMEDIOAPLI)
    FROM AD_FCICOMP
    WHERE ORIGEMMPREF IN ('1','2','3','6','7','8')
    AND CODPRODPA = COM.CODPRODPA),0) VLRPARCIMP,
    PRO.ORIGPROD ORIGPRODATUAL,
CASE WHEN NVL((SELECT VLRMEDIO 
    FROM AD_FCISAIDA 
    WHERE NUNICO = COM.NUNICO
    AND CODPROD = COM.CODPRODPA),0) >0 THEN
ROUND((NVL((SELECT SUM(VLRMEDIOAPLI)
    FROM AD_FCICOMP
    WHERE ORIGEMMPREF IN ('1','2','3','6','7','8')
    AND CODPRODPA = COM.CODPRODPA),0)*100)/NVL((SELECT VLRMEDIO 
    FROM AD_FCISAIDA 
    WHERE NUNICO = COM.NUNICO
    AND CODPROD = COM.CODPRODPA),1),2) ELSE 0 END PERCIMPORTADO,
    PRO.VLRCOMERC OLDVLRCOMERC,
	PRO.VLRPARCIMPEXT

   



FROM AD_FCICOMP COM 
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = COM.CODPRODPA
WHERE NUNICO = :P_NUNICO)